{
 "title": "Detailed Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(process_runtime_jvm_cpu_utilization_ratio,job)"
    }
   },
   {
    "name": "node_id",
    "label": "Node Id",
    "query": {
     "query": "label_values(process_runtime_jvm_cpu_utilization_ratio,instance)"
    }
   },
   {
    "name": "request_type",
    "label": "Kafka Request",
    "query": {
     "query": "label_values(kafka_request_count_total,type)"
    }
   },
   {
    "name": "s3stream_request",
    "label": "S3Stream Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Stream\"},operation_name)"
    }
   },
   {
    "name": "s3request",
    "label": "S3 Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Request\"},operation_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_cpu_utilization_ratio{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $C", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "NodeNode-{{instance}}#allocated"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_used_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#used"
    },
    { "expression": "1 - $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation Detailed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance, type) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Cache Size (DEBUG)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_delta_wal_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Delta_WAL_Cache"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_block_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Block_Cache"
    }
   ]
  },
  { "title": "Kafka Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, job, type) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "IO Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_io_threads_idle_rate_1m{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Network Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_network_threads_idle_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  { "title": "S3Stream Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, operation_type) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "S3 Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation_name, instance) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "Delta WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal|append_wal_full\", operation_type=\"S3Storage\", stage=\"complete\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}_Avg"
    },
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}_P99"
    }
   ]
  },
  { "title": "Delta WAL Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache|append_log_cache_full\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Storage\", operation_name=\"read_log_cache\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  { "title": "Upload WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Upload WAL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}_Avg"
    },
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}_P99"
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"read_block_cache\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_block_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}_P99"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Read Ahead Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_ahead\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, status) (rate(kafka_stream_read_ahead_size_sum_bytes{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_ahead\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}_P99"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Read Ahead Size Avg",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance) (kafka_stream_read_ahead_size_mean_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}"
    },
    {
     "expr": "avg by(instance) (kafka_stream_read_ahead_size_99p_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#P99"
    }
   ]
  },
  {
   "title": "Available Inflight Read Ahead Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_available_inflight_read_ahead_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Read Ahead Stage Latency (DEBUG)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Read Block Cache Miss Stage Latency (DEBUG)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Read Block Cache Hit Stage Latency (DEBUG)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Get Indices Latency (DEBUG)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Total Bytes In / Out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_inbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_outbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  {
   "title": "Bytes In / Out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_download_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_S3"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_upload_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_S3"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_Msg"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"out\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_Msg"
    }
   ]
  },
  {
   "title": "Available Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (kafka_stream_network_inbound_available_bandwidth_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "sum by(instance, job) (kafka_stream_network_outbound_available_bandwidth_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  {
   "title": "Network Limiter Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance) (kafka_stream_network_inbound_limiter_queue_time_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_Avg"
    },
    {
     "expr": "avg by(instance) (kafka_stream_network_outbound_limiter_queue_time_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Out_Avg"
    },
    {
     "expr": "avg by(instance) (kafka_stream_network_inbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_P99"
    },
    {
     "expr": "avg by(instance) (kafka_stream_network_outbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Out_P99"
    }
   ]
  },
  { "title": "S3 Object", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "S3 Object Count Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 197 },
   "targets": [
    {
     "expr": "sum by(state) (kafka_stream_s3_object_count{job=\"$cluster_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Object Size Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_stream_s3_object_size_bytes{job=\"$cluster_id\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "StreamSetObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 209 },
   "targets": [
    {
     "expr": "sum by(node_id) (kafka_stream_stream_set_object_num{job=\"$cluster_id\", node_id=~\"$node_id\"})",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  },
  {
   "title": "StreamObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 209 },
   "targets": [
    {
     "expr": "kafka_stream_stream_object_num{job=\"$cluster_id\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Get Object Throughput By Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=\"get_object\", job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Get Object Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, size) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=\"get_object\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{size}}"
    }
   ]
  },
  {
   "title": "Get Object Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=\"get_object\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Throughput By Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Put Object Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, size) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\"})",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Put Object Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\"})",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 247 } },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_compaction_read_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "rate(kafka_stream_compaction_write_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  { "title": "Auto-Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 262 } },
  {
   "title": "Metrics Delay",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_auto_balancer_metrics_time_delay_milliseconds{job=\"$cluster_id\", node_id=~\"$node_id\"}",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  }
 ]
}